first commit
Pikafarad/WidgetMovement pull request #1
Opened 2024-04-01 09:44 UTC by Pikafarad

2024-04-01 16:14 UTC, Toxin65 commented on mainwindow.cpp
> +    auto tm_1 = new QTimer();
Владение ничьё, так неправильно, кто его удалять будет?

2024-04-01 16:15 UTC, Toxin65 commented on mainwindow.cpp
> +    tm_1->setInterval(1000);
Нарушение требования ТЗ, период создания кнопок произвольный в определённом диапазоне.

2024-04-01 16:16 UTC, Toxin65 commented on mainwindow.cpp
> +        tmStart->setSingleShot(true);
Синглшот не нужен. Я понял, таймер который выше -- он лишний.

2024-04-01 16:17 UTC, Toxin65 commented on mainwindow.cpp
> +        auto tmStart = new QTimer(this);
А зачем по первому таймеру создаётся куча вторичных, которые создают кнопки?

2024-04-01 16:18 UTC, Toxin65 commented on mainwindow.cpp
> +                pb->setGeometry(x, y ,50, 50);
Надо бы `50` утащить в константу, раз они зависимые друг от друга, ведь выше те же самые 50 написаны.

2024-04-01 16:19 UTC, Toxin65 commented on mainwindow.cpp
> +                tm->setInterval(30);
А почему именно 30?

2024-04-01 16:20 UTC, Toxin65 commented on mainwindow.cpp
> +                        this->setAutoFillBackground(true);
`this->` писать не надо, когда мы захватываем `this` в лямбду синтаксис как в методах класса.

2024-04-01 16:21 UTC, Toxin65 commented on mainwindow.cpp
> +            tmStart->start();
Соответственно рестартить таймер не нужно.

2024-04-01 16:21 UTC, Toxin65 requested changes
Лишний таймер, перемудрёно. Упростить, почистить.

2024-04-02 03:01 UTC, Pikafarad commented on mainwindow.cpp
> +                tm->setInterval(30);
Чтобы картинка плавнее была, но тут я понял, что на кнопку тогда сложнее нажать

2024-04-02 13:01 UTC, Toxin65 commented on mainwindow.cpp
> +                tm->setInterval(30);
Дело не в этом, думаю есть смысл исходить из частоту обновления изображения... А 30... ни туда ни сюда...

2024-04-02 13:05 UTC, Toxin65 commented on mainwindow.cpp
> +            QRandomGenerator *rg = QRandomGenerator::global();
Вы же его захватили, зачем опять его вытаскивать?

2024-04-02 13:06 UTC, Toxin65 commented on mainwindow.cpp
> +            tm->setInterval(100);
Почему 100?

2024-04-02 13:07 UTC, Toxin65 commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
Почему это здесь?

2024-04-02 13:10 UTC, Toxin65 commented on mainwindow.cpp
> +                    show();
Что это?

2024-04-02 13:11 UTC, Toxin65 commented on mainwindow.cpp
> +
Это нужно? И выше.

2024-04-02 13:11 UTC, Toxin65 requested changes
Серьёзные ошибки и много непонимания. Разберитесь.

2024-04-02 13:58 UTC, Pikafarad commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
а как кнопка тогда должна исчезать при клике на нее?

2024-04-02 14:01 UTC, Pikafarad commented on mainwindow.cpp
> +            tm->setInterval(100);
если монитор 60 гц, получается нужно выставлять 0,16?

2024-04-02 14:03 UTC, Pikafarad commented on mainwindow.cpp
> +            tm->setInterval(100);
если монитор 60 гц, то интервал будет 17 мс?

2024-04-02 14:05 UTC, Pikafarad commented on mainwindow.cpp
> +                    show();
Убрал, оказалось лишнее

2024-04-02 14:06 UTC, Toxin65 commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
Кнопка правильная, а почему коннект то здесь?

2024-04-02 14:07 UTC, Toxin65 commented on mainwindow.cpp
> +            tm->setInterval(100);
Да, примерно с этого и надо начинать... Можно так.
Но 10 Гц это конечно много.

2024-04-02 14:15 UTC, Pikafarad commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
Можно через pb->isDown(), понял

2024-04-02 14:29 UTC, Toxin65 commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
Нет... Коннект в неправильном месте. Сколько раз он обрабатывает?

2024-04-02 14:30 UTC, Pikafarad commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
Много...

2024-04-02 14:34 UTC, Pikafarad commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
Лучше перенести его за пределы таймера

2024-04-02 14:34 UTC, Toxin65 commented on mainwindow.cpp
> +                connect(pb, &QPushButton::clicked, pb, &QPushButton::deleteLater);
Ну дак а почему много? Он сколько раз должен отработать?

2024-04-02 16:51 UTC, Toxin65 commented on mainwindow.cpp
> +        tmStart->start(rg_2->bounded(100, 1000));
NIT отступ поехал.

2024-04-02 16:52 UTC, Toxin65 commented on mainwindow.cpp
> +            int y = rg_2->bounded(0, 100);
Всё, что можно делается либо `const` либо `constexpr`
В данном случае `const`, а вот выше с константами `constexpr`

2024-04-02 16:54 UTC, Toxin65 commented on mainwindow.cpp
> +            tm->setInterval(17);
Лучше тогда писать выражение, как вы это получили, т.е. `1000/60` и написать коммент, что 60 -- это частота обновления изображения не дисплее. Тогда ваши последователи обслуживая этот код будут понимать почему так.

2024-04-02 16:55 UTC, Toxin65 commented on mainwindow.cpp
> +                if(pb->pos().y() >= this->height()-pb->height())
Пропустили `this->` и ниже.

2024-04-02 16:58 UTC, Toxin65 approved these changes
Замечания учесть. В целом код стал нормальный.
Это 9/10 за время и за кучу замечаний.
Но вы хорошо потрудились!

И ещё, вы не указали кто вы, а в профиле я не увидел (может плохо смотрел)

2024-04-02 17:03 UTC, Pikafarad commented
Завтра исправлю, спасибо, было интересно, в профиле похоже имя не указал, Исмагилов Дамир

2024-04-02 17:07 UTC, Toxin65 commented
> Завтра исправлю, спасибо, было интересно, в профиле похоже имя не указал, Исмагилов Дамир

Ксении оценку отправил. Удачи, вы учитесь, и это хорошо!
Буду рад вашим успехам!

2024-04-03 02:45 UTC, merged